import test from 'node:test';
import assert from 'node:assert/strict';
import {districts,examples,demoAnalysis,seedRequests,priorities,brief,validateAnalysis} from '../backend/src/logic.mjs';
test('three supported demo samples retain their language and intended categories',()=>{assert.equal(demoAnalysis(examples.English).category,'Water');assert.equal(demoAnalysis(examples.Hindi).language,'Hindi');assert.equal(demoAnalysis(examples.Hindi).category,'Water');assert.equal(demoAnalysis(examples.Kannada).language,'Kannada');assert.equal(demoAnalysis(examples.Kannada).category,'Roads');});
test('unknown requests stay Other instead of inventing a category',()=>assert.equal(demoAnalysis('Please consider this suggestion.').category,'Other'));
test('priority scores stay bounded and respond to local demand',()=>{const base=priorities([]);const added=priorities(Array.from({length:1000},()=>({district:'mysuru',category:'Water'})));assert(added.find(d=>d.id==='mysuru').score>base.find(d=>d.id==='mysuru').score);assert(added.every(d=>d.score>=0&&d.score<=100));assert.equal(added.find(d=>d.id==='raichur').score,base.find(d=>d.id==='raichur').score);assert.equal(added.find(d=>d.id==='mysuru').demand,100);});
test('template brief uses the same district count and score as dashboard',()=>{const list=seedRequests();for(const d of priorities(list)){const result=brief(list,d.id);assert(result.includes(`Priority score: ${d.score}/100`));assert(result.includes(`Requests: ${d.count}`));assert(result.includes('synthetic'));}});
test('model output requires known category and text fields',()=>{assert.throws(()=>validateAnalysis({category:'Emergency funding'}));assert.throws(()=>validateAnalysis({category:'Water',summary:4,language:'English',transcript:'a'}));assert.equal(validateAnalysis({category:'Water',summary:'Repair pump',language:'English',transcript:'pump'}).source,'Gemini on Vertex AI');});
test('all seeded rows have unique text per district and valid district references',()=>{const rows=seedRequests();assert.equal(new Set(rows.map(r=>r.district+r.text)).size,rows.length);assert(rows.every(r=>districts.some(d=>d.id===r.district)));});
